ignored = ["github.com/Sirupsen/logrus"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.5"

[[constraint]]
  name = "k8s.io/api"
  revision = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.10.0"

[[constraint]]
  name = "github.com/dcos/dcos-go"
  revision = "master"

[[constraint]]
  name = "github.com/mesosphere/dcos-commons"
  revision = "0.42.0"

[[constraint]]
  name = "github.com/mesosphere/dcos-edge-lb"
  branch = "ack/https-only"